# Somewhat temporary

TolkienDict = {
    'thing': [
        'the fellowship of the ring',
        'last alliance of Elves and Men',
        'eagle',
        'broken sword',
        'tower',
        'mountain',
        'hill',
        'bulwark',
        'bend',
        'Barrow-wight',
        'ring',
        'bow',
        'sword',
        'dagger',
        'catapult',
        'battering ram',
        'mace',
        'axe',
        'darkness',
        'light',
        'stone',
        'balrog',
        'troll',
        'Lembas bread',
        'Nazgul',
    ],
    'speciesSingular': [
        'Elf',
        'Dwarf',
        'Man',
        'Orc',
        'Ent',
        'Hobbit',
    ],
    'speciesPlural': [
        'Elves',
        'Dwarves',
        'Men',
        'Orcs',
        'Ents',
        'Hobbits',
        'Nazgul',
    ],
    'place': [
        'Mordor',
        'Hobbiton',
        'The Shire',
        'Minas Tirith',
        'Minas Morgul',
        'The Undying Lands',
        'Gondor',
        'Mirkwood',
        'Bree',
        'The Crack of Doom',
        'Lothlurien',
        'Weathertop',
        'The mines of Moria',
        'Grey Havens',
        'Helm\'s Deep',
        'Isengard',
        'Khazad-dum',
        'Lorien',
        'Minas Ithil',
        'Minas Morgul',
        'Rivendell',
    ],
    'person': [
        'Theoden',
        'Frodo',
        'Bilbo',
        'Sauron',
        'Legolas',
        'Gimli',
        'Gandalf',
        'Saruman',
        'Sam',
        'Pippin',
        'Farmer Maggot',
        'Merry',
        'Aragorn',
        'Boromir',
        'Elrond',
        'Galadriel',
        'Eomer',
        'Eowyn',
        'Faramir',
        'Arwen',
        'Radagast',
        'Morgoth',
        'The Witch King',
        'Gollum',
        'Grima Wormtongue',
        'Smaug',
        'Shelob',
    ],
    'verbPresent': [
        'sing',
        'form',
        'build',
        'pound',
        'smash',
        'fall',
        'forge',
        'climb',
        'attack',
    ],
    'verbPast': [
        'formed',
        'pounded',
        'smashed',
        'fell',
        'forged',
        'sounded',
        'slaughtered',
    ],
    'exclamation': [
        'Listen',
        'Quick',
    ],
}

TolkienSentenceFormats = [
    'A {thing} {verbPast}.',
    'In {place}, a {thing} was {verbPast}.',
    '"{exclamation}!", cried {person}, "{speciesPlural}!"',
    '{person} {verbPast} the {thing}.',
    '{medNumber} {speciesPlural} came over the {thing}.',
    'The {speciesPlural} hurried to {place}.',
    '{smallNumber} {thing} were {verbPast}.',
    '{smallNumber} {speciesPlural} joined to {verbPresent} the {thing}.',
    'The {speciesPlural} rallied around the {thing}.',
    '{person} felt he did not have the strength to {verbPresent}.',
    '{person} led the {speciesPlural} to {place} to {verbPresent}.',
    '{person} led the {speciesPlural} to attack {place}, but the attack failed.',
    'The {speciesSingular} women and children hurried to {place} for shelter.',
    'The attack failed, forcing the {speciesPlural} to retreat to {place}.',
    '{person} insisted on attacking {place}, but the {speciesPlural} were waiting.',
    '{person} attacked {place}, and slaughtered the {speciesPlural} in a surprise attack.',
    '{person} was found full of arrows.',
    'The {speciesPlural} ambushed {person} at {place}.',
    'The {speciesPlural} were ravaging the countryside, leaving destruction in their wake.',
]

