# Somewhat temporary

TolkienDict = {
    'thing': [
        'last alliance of Elves and Men',
        'broken sword',
        'tower',
        'mountain',
        'ring',
        'bow',
        'sword',
        'dagger',
        'catapult',
        'battering ram',
        'mace',
        'axe',
        'darkness',
        'light',
        'stone',
    ],
    'speciesSingular': [
        'Elf',
        'Dwarf',
        'Man',
        'Orc',
        'Ent',
        'Hobbit',
        'Nazgul',
    ],
    'speciesPlural': [
        'Elves',
        'Dwarves',
        'Men',
        'Orcs',
        'Ents',
        'Hobbits',
        'Nazgul',
    ],
    'place': [
        'Mordor',
        'Hobbiton',
        'The Shire',
        'Minas Tirith',
        'Minas Morgul',
        'The Undying Lands',
        'Gondor',
        'Mirkwood',
        'Bree',
        'Crack of Doom',
        'Lothlurien',
        'Weathertop',
        'The mines of Moria',
    ],
    'person': [
        'Theoden',
        'Frodo',
        'Bilbo',
        'Sauron',
        'Legolas',
        'Gimli',
        'Gandalf',
        'Saruman',
        'Sam',
        'Pippin',
        'Farmer Maggot',
    ],
    'verbPresent': [
        'sing',
        'form',
        'build',
        'pound',
        'smash',
        'fall',
        'forge',
    ],
    'verbPast': [
        'sang',
        'formed',
        'pounded',
        'smashed',
        'fell',
        'forged',
        'sounded',
    ],
    'exclamation': [
        'Look',
        'Listen',
        'Quick',
    ],
}

TolkienSentenceFormats = [
    'In {largeNumber}, a {thing} {verbPast}.',
    'In {place}, a {thing} {verbPast}.',
    '"{exclamation}!", cried {person}, "{speciesPlural}!"',
    '"{exclamation}!", cried {person}, "A {speciesSingular}!"',
    'Meanwhile, {person} {verbPast} the {thing}.',
    '"Ha! My {thing} will {verbPresent} you dead!", said {person}.',
    '{medNumber} {speciesPlural} came over the {thing}.',
    'The {speciesPlural} hurried to {place}.',
    '{smallNumber} {thing}s {verbPast}.',
    '{smallNumber} {speciesPlural} joined to {verbPresent} the {thing}.'
]

